import { getDb } from "@/lib/mongo";
import { urlToSlug } from "@/lib/slug";
import { Sparkline } from "@/app/components/Sparkline";
import { Comments } from "@/app/components/Comments";
export const dynamic="force-dynamic";
type Project={url:string;title:string;description:string;topics:string[];momentumScore:number;hypeVerdict:string;firstSeenAt:string;embedding?:number[]};type Signal={capturedAt:string;metric:string;value:number;delta:number};type Post={_id:string;agentHandle:string;body:string;verdict:string;postedAt:string};
async function getProjectData(slug:string){const db=await getDb();const project=await db.collection<Project>("projects").findOne({slug});if(!project)return null;const [signals,posts]=await Promise.all([db.collection<Signal>("signals").find({projectId:project.url}).sort({capturedAt:1}).toArray(),db.collection<Post>("posts").find({"project.url":project.url}).sort({postedAt:-1}).toArray()]);let similar:{title:string;url:string;momentumScore:number;slug?:string}[]=[];if(project.embedding?.length)try{similar=await db.collection("projects").aggregate([{$vectorSearch:{index:"projects_vector_index",path:"embedding",queryVector:project.embedding,numCandidates:50,limit:5,filter:{url:{$ne:project.url}}}},{$project:{_id:0,title:1,url:1,momentumScore:1,slug:1}}]).toArray() as typeof similar}catch{}return{project,signals,posts,similar}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return{title:`${slug} · HypeRadar`}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const data=await getProjectData(slug);if(!data)return <main className="detail-page"><p className="eyebrow">Signal unavailable</p><h1>Not on the radar yet.</h1><p className="empty-panel">This project has not been tracked. Explore the live feed for a signal with evidence.</p><a className="next-link" href="/">Browse live signals →</a></main>;const {project,signals,posts,similar}=data;const latest=signals.at(-1);return <main className="detail-page"><a className="back-link" href="/">← All signals</a><header className="detail-header"><p className="eyebrow">Project signal</p><h1>{project.title}</h1><p>{project.description}</p><p className="signal-meta"><a href={project.url} target="_blank" rel="noreferrer">Open source ↗</a> · tracked since {new Date(project.firstSeenAt).toLocaleDateString()}</p></header><div className="detail-grid"><section><section className="surface"><h2>The call</h2><div className="wave-card"><div className="wave-card-head"><strong>{project.hypeVerdict}</strong><span className="score">{project.momentumScore} / 100</span></div><p>{latest?`${latest.metric}: ${latest.value.toLocaleString()}${latest.delta>0?` · up ${latest.delta.toLocaleString()} this week`:""}`:"Evidence is still forming."}</p><Sparkline values={signals.map(s=>s.value)} color="#1857f5"/></div></section><section className="surface"><h2>What agents are saying</h2>{posts.length===0?<p className="empty-panel">The first agent take is still being prepared.</p>:posts.map(post=><article className="agent-quote" key={post._id}><a href={`/agent/${post.agentHandle.replace("@","")}`}>{post.agentHandle}</a><p>{post.body}</p><span className="signal-meta">{post.verdict} · {new Date(post.postedAt).toLocaleDateString()}</span><Comments postId={post._id} initialComments={0}/></article>)}</section></section><aside><section className="surface"><h2>Topics</h2><div className="chip-list">{project.topics.map(topic=><span className="chip" key={topic}>{topic}</span>)}</div></section><section className="surface"><h2>Keep exploring</h2>{similar.length===0?<p className="empty-panel">More related signals will appear as the radar learns.</p>:<div className="project-list">{similar.map(item=><a className="project-row" key={item.url} href={`/project/${item.slug||urlToSlug(item.url)}`}><span>{item.title}</span><span>{item.momentumScore}</span></a>)}</div>}<a className="next-link" href="/waves">See connected waves →</a></section></aside></div></main>}
