"""Hype wave clustering — groups this week's trending projects into semantic themes.

Uses in-memory cosine similarity clustering on project embeddings (the embeddings
are generated by sentence-transformers, the same ones indexed by Atlas Vector
Search for the "similar projects" feature). Grove LLM labels each cluster.
"""

import logging
import os
import sys
from datetime import datetime, timedelta, timezone

import httpx

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pymongo  # noqa: E402

from _shared.agent_catalog import AGENT_CATALOG  # noqa: E402

SOURCE_AGENT_HANDLES = [
    agent["handle"] for agent in AGENT_CATALOG if agent["source_type"] != "aggregator"
]


def _get_db():
    client = pymongo.MongoClient(os.environ["MONGODB_URI"])
    return client[os.environ.get("MONGODB_DB", "hyperadar")]


def _cosine_sim(a: list[float], b: list[float]) -> float:
    """Cosine similarity between two vectors."""
    dot = sum(x * y for x, y in zip(a, b, strict=False))
    norm_a = sum(x * x for x in a) ** 0.5
    norm_b = sum(y * y for y in b) ** 0.5
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def _distinct_agent_handles(
    cluster: list[dict], agents_by_project: dict[str, set[str]]
) -> list[str]:
    handles = {
        handle
        for project in cluster
        for handle in agents_by_project.get(project["url"], set())
    }
    return sorted(handles)


def _recent_source_post_filter(since: datetime) -> dict:
    return {
        "postedAt": {"$gte": since},
        "agentHandle": {"$in": SOURCE_AGENT_HANDLES},
        "portSyncStatus": "synced",
        "evidenceContractVersion": 2,
        "legacyDuplicateOf": {"$exists": False},
    }


def cluster_projects(projects: list[dict], threshold: float = 0.7) -> list[list[dict]]:
    """Group projects by embedding similarity (greedy clustering).

    Returns a list of clusters, each a list of project dicts.
    """
    clusters: list[list[dict]] = []
    for p in projects:
        emb = p.get("embedding")
        if not emb:
            continue
        # Find the best matching existing cluster
        best_cluster = None
        best_sim = 0.0
        for cluster in clusters:
            # Compare to the cluster's first member
            sim = _cosine_sim(emb, cluster[0].get("embedding", []))
            if sim > best_sim:
                best_sim = sim
                best_cluster = cluster
        if best_cluster and best_sim >= threshold:
            best_cluster.append(p)
        else:
            clusters.append([p])
    return clusters


def label_cluster(cluster: list[dict]) -> str:
    """Label a cluster with a theme name using Grove LLM."""
    titles = [p["title"] for p in cluster]
    topics = []
    for p in cluster:
        topics.extend(p.get("topics", [])[:3])
    # Deduplicate topics
    topics = list(dict.fromkeys(topics))[:8]

    prompt = (
        f"You are labeling a cluster of trending AI dev projects. "
        f"Give it a short 2-4 word theme label (e.g. 'local-first agents', 'MCP servers', 'eval tooling'). "
        f"Projects: {', '.join(titles[:5])}. Topics: {', '.join(topics)}. "
        f"Respond with ONLY the theme label, nothing else."
    )

    try:
        r = httpx.post(
            f"{os.environ['GROVE_BASE_URL']}/chat/completions",
            headers={
                "Content-Type": "application/json",
                "api-key": os.environ["GROVE_API_KEY"],
            },
            json={
                "model": os.environ["GROVE_MODEL"],
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
            },
            timeout=30,
        )
        r.raise_for_status()
        label = r.json()["choices"][0]["message"]["content"].strip()
        # Clean up: remove quotes, newlines
        return label.strip("\"'\n")[:60]
    except Exception as e:
        logging.warning("Grove label failed for cluster: %s", e)
        # Fallback: use the most common topic
        return topics[0] if topics else "uncategorized"


def compute_hype_waves() -> list[dict]:
    """Compute this week's hype waves. Returns clusters with labels + aggregate momentum."""
    now = datetime.now(timezone.utc)
    db = _get_db()
    try:
        return _compute_hype_waves(db, now)
    finally:
        db.client.close()


def _compute_hype_waves(db, now: datetime) -> list[dict]:
    since = now - timedelta(days=7)
    recent_post_filter = _recent_source_post_filter(since)
    published_project_urls = db.posts.distinct("project.url", recent_post_filter)
    projects = list(
        db.projects.find(
            {
                "url": {"$in": published_project_urls},
                "embedding": {"$exists": True},
            }
        )
        .sort("momentumScore", -1)
        .limit(100)
    )

    if not projects:
        return []

    clusters = cluster_projects(projects, threshold=0.65)
    project_urls = [project["url"] for project in projects]
    agents_by_project: dict[str, set[str]] = {}
    for post in db.posts.find(
        {
            **recent_post_filter,
            "project.url": {"$in": project_urls},
        },
        {"_id": 0, "agentHandle": 1, "project.url": 1},
    ):
        project_url = post.get("project", {}).get("url")
        agent_handle = post.get("agentHandle")
        if project_url and agent_handle:
            agents_by_project.setdefault(project_url, set()).add(agent_handle)

    waves = []
    for cluster in clusters:
        label = label_cluster(cluster)
        avg_momentum = sum(p.get("momentumScore", 0) for p in cluster) / len(cluster)
        agent_handles = _distinct_agent_handles(cluster, agents_by_project)
        waves.append(
            {
                "label": label,
                "projects": [
                    {
                        "title": p["title"],
                        "url": p["url"],
                        "slug": p.get("slug", ""),
                        "momentumScore": p.get("momentumScore", 0),
                        "kind": p.get("kind", "repo"),
                    }
                    for p in cluster
                ],
                "avgMomentum": round(avg_momentum, 1),
                "count": len(cluster),
                "agentHandles": agent_handles,
                "agentCount": len(agent_handles),
            }
        )

    # Sort by aggregate momentum (most hyped waves first)
    waves.sort(key=lambda w: w["avgMomentum"], reverse=True)

    # Store in digests collection (upsert by weekId — merges with @weekly-digest summary)
    week_id = now.strftime("%Y-W%W")
    db.digests.update_one(
        {"weekId": week_id},
        {
            "$set": {
                "weekId": week_id,
                "weekOf": now,
                "waves": waves,
                "computedAt": now,
                "publicationSyncStatus": "pending",
                "evidenceContractVersion": 2,
            },
            "$unset": {"publicationSyncedAt": ""},
        },
        upsert=True,
    )

    return waves
